### ISSUE TITLE
rename the Operations SIG to AIOps SIG 

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#1109]
@jiri-fiala @wgordon17 

Could we re-jig the landing page (https://github.com/openshift-cs/commons.openshift.org/blob/master/source/sig/Operations.html.erb) so that it's called https://github.com/openshift-cs/commons.openshift.org/blob/master/source/sig/AIOps.html.erb instead 

change the title to  "AIOps
The principal purpose of the OpenShift Commons AIOps Special Interest Group is to collaborate and share information around best practices for applying AI to the task associated with operating and maintaining large scale OpenShift environments."

change the string "Join the OpenShift Operations Special Interest Group" to "Join the AIOps
Special Interest Group

remove the section called "OpenShift Ops Commons Briefing" from the landing page

rename the section currently called "OpenShift Ops Articles" to "AIOps Articles" and pick up any openshift blog post that are tagged with either "AIOps" or "AI" 

fyi: @durandom

**Comment by jiri-fiala** [comment]
@dmueller2001, please [preview](https://com-stage-pro.b9ad.pro-us-east-1.openshiftapps.com/sig/AIOps.html) and approve the change.

Additionally to what was requested in the issue, I've made these changes:
- Changed the Ops link on the [index page](https://com-stage-pro.b9ad.pro-us-east-1.openshiftapps.com/index.html) to AIOps, reworded the subtitle as _"Discuss, develop and disseminate best practices for AI driven OpenShift environment maintenance"_
- Changed the _"Machine Learning on OpenShift"_ title to just _"Machine Learning"_ (one liner), in order to align it with the new _AIOps_ on the same row
- Added a redirect from `sig/Operations.html` to `sig/AIOps.html`
- Removed the obsolete section about Zabbix monitoring scripts (pointing to https://github.com/openshift/openshift_zabbix) and Puppet modules (pointing to https://github.com/openshift/puppet-openshift_origin)

---

This requires an update on the Eloqua side too, I believe. The universal SIG sign up form is processing submissions based on the URL, so the change from `/sig/Operations.html` to `/sig/AIOps.html` needs to be addressed. Please let us know if this is something you're up to.

**Comment by durandom** [comment]
@dmueller2001 is this good to merge?

**Comment by dmueller2001** [comment]
I went in made the edits and renamed the urls on the index.html page as well..and made the changes myself today..so this is no longer required.
@jiri-fiala 

you wrote "This requires an update on the Eloqua side too, I believe. The universal SIG sign up form is processing submissions based on the URL, so the change from /sig/Operations.html to /sig/AIOps.html needs to be addressed. Please let us know if this is something you're up to."

The join form works without having ask for anything from the Eloqua team. 

Thanks,
Diane
