### ISSUE TITLE
https://commons.openshift.org/sig/OpenshiftEnergy.html not appearing

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#1218]
I edit index.html.erb and create OpenShiftEnergy.html.erb and removed BigData.html.erb reference in index.html.erb 

I believe I did the edits correctly, but the https://commons.openshift.org/sig/OpenshiftEnergy.html is not appearing..

could you check my work?

**Comment by jiri-fiala** [comment]
@dmueller2001, the page name is OpenShiftEnergy.html (capitalized `S`, rather than OpenShiftEnergy.html). This typo has been [fixed for the Index link by Will](https://github.com/openshift-cs/commons.openshift.org/commit/f6948c9a2eacba23b890c9bc0eced3e887bbd511) already, I have updated the breadcrumbs link on the SIG page itself and added a general "OpenShift Ecosystem" articles to the page. If you have a better tag or category, please open a separate issue to have this updated
