### ISSUE TITLE
add immaco.fi to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#820]
company: Immaco
url: http://immaco.fi/
logo: ![immaco](https://user-images.githubusercontent.com/22222756/46824231-34210800-cd5e-11e8-96ac-20c3eb4cee72.png)

@jiri-fiala @wgordon17

**Comment by wgordon17** [comment]
@dmueller2001 Can you ask participant if they would be OK with using the following as their logo?

Taken from their website:
![immaco](https://user-images.githubusercontent.com/22222756/46021506-d9758400-c0ae-11e8-9e03-045d9778bc59.png)

Otherwise we have to do some additional work on the commons page to support non-logo participants.

**Comment by wgordon17** [comment]
@dmueller2001 bump?
