### ISSUE TITLE
This is Event is Now Over message appearing prematurely on London Event!!!

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#964]
This is Event is Now Over message appearing prematurely on London Event; the https://github.com/openshift-cs/commons.openshift.org/blob/master/data/gatherings.yml appears to have the 'correct' date for the event - and we are doing a big push this month to promote the event..

![thiseventisnowoverpremature](https://user-images.githubusercontent.com/4029488/50565277-1a9ab700-0ce2-11e9-95d6-4969a9dfab2f.png)

url:
https://commons.openshift.org/gatherings/London_2019.html

@jiri-fiala @wgordon17

**Comment by wgordon17** [comment]
Hey @dmueller2001, this appears to no longer be an issue. Can you confirm it's fixed on your end as well?

**Comment by jiri-fiala** [comment]
I can't induce it presently either. According to the screenshot, it seems like the css for the [`gathering-over-notice`](https://github.com/openshift-cs/commons.openshift.org/blob/master/source/gatherings/template.html.erb#L94) was not applied at all (hiding it and styling properly), rather a cached css version (Nov 30 or older) was used instead. We currently don't hash-name assets on build, which would prevent such outdated css from being used (if this issue was indeed fixed by cache-less reload in the same browser, where you originally induced it, @dmueller2001).

**Comment by dmueller2001** [comment]
looks to have been resolved! thanks for checking it out!
